version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: fono_dev_db     
      POSTGRES_USER: fono_user     
      POSTGRES_PASSWORD: fono_password 
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local